name: Vitalz
main: me.marthi.vitalz.vitalz
version: 1
authors: ["rcth", "ipsq", "jessedevries20"]
description: Vitalz is the new Bukkit-core plugin with alot of useful commands
commands:
    pl:
      description: Show you a list of plugins used on the server
      usage: /<command>
      aliases: plugins
    help:
      description: View a list of availible commands
      usage: /<command> [page]
    vitalz:
      description: Shows information about this plugin
      usage: /<command>
    vanish:
      description: Make a player invisible
      usage: /<command> [player]
    fly:
      description: Woosh, fly in the air!
      usage: /<command> [player]
    time:
      description: Set the time in a specific world
      usage: /<command> [day/morning/night/timestep] [world]
    top:
      description: Teleport you to the highest block at your location
      usage: /<command>
    ping:
      description: You like pingpong too?
      usage: /<command>
    gamemode:
      description: Change the gamemode of a specific player
      usage: /<command> <0/1/2/survival/creative/adventure/s/c/a>
      aliases: [gm, mode]
    tp:
      description: Teleport somebody to another player
      usage: /<command> <target>